#!/usr/bin/env bash
## Autostart Programs

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Set wallpaper
~/.config/hypr/scripts/wallpaper &

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &

#exec abc &
